name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

 
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
         SYNK_TOKEN: $ {{ secrets.SYNK_TOKEN }}
        
        
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch from github
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
         
      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          mkdir downloads && cp target/*.war downloads
      
      - name: target folder
        run: |
          cd target
          ls -a
          
      - name: Download the Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: upload artifacts with github actions
          path: downloads
            
          
          
          
        


