name: Trigger Bisleri Repo Workflow

on:
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Bisleri Repository Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
               --data '{"event_type":"trigger-event"}' \
               https://api.github.com/repos/Anudeepkumar02/Bisleri/dispatches
